### ISSUE TITLE
Scan problem

### ISSUE THREAD

**Issue by HeriKuen** [firemaples/EverTranslator#123]
1. Problems with Japanese or Kanji translations.
2. Light differences sometimes also affect the results of the translation.
thanks for making this aplication.

**Comment by firemaples** [comment]
Thanks for your like and sorry for the late response.
I'm trying to find an alternative service to recognize Japanese more correctly.

**Comment by firemaples** [comment]
#146

**Comment by firemaples** [comment]
The next release version will fix this issue by changing the OCR engine to a more accurate one.
