### ISSUE TITLE
Please merge the OCR results in one line

### ISSUE THREAD

**Issue by bregassa** [firemaples/EverTranslator#176]
I use EverTranslator + Papago mini for reading Korean webtoon. EverTranslator does a good job on recognizing KR character.
But it will be great if you can make the OCR result merged in one line, because the KR will be translated separately if it's not in one line and will results to bad translation.

So the current results when I scan a text bubble is gonna be like this :
그럼 뭐 어째.
애가 셋인데
같이 안 살고 배겨?

Please make it so it will be merge in one line like this so it will result to better translation :
그럼 뭐 어째. 애가 셋인데 같이 안 살고 배겨? 

Thanks for your great work, keep it up!

**Comment by bregassa** [comment]
Or maybe you can make a dedicated setting toggle for this so user can choose if they want the OCR results to be separated or merged in one lines. Goodluck~

**Comment by firemaples** [comment]
#168 
Thanks for your feedback, I'll make it an option to the settings page.
