### ISSUE TITLE
翻譯失敗

### ISSUE THREAD

**Issue by InitialXKO** [firemaples/EverTranslator#18]
[microsoft-translator-api] Error retrieving translation: https://api.cognitive.microsoft.com/sts/v1.0/issueToken

**Comment by firemaples** [comment]
目前因為 Microsoft translator 僅使用 free plan，每個月只有 200 萬個字的翻譯上限，雖然有開了三個帳號來分流，但還是在 10 天左右用量就用完了 (上個月使用者還沒這麼多)

目前考慮增加新的翻譯引擎來分流使用者

**Comment by firemaples** [comment]
#3
