### ISSUE TITLE
Got error! when using translation twice and later

### ISSUE THREAD

**Issue by wres168** [firemaples/EverTranslator#194]
When using translation twice and later, it will get an error: "attempt to invoke interface method 'boolean java.util.set.add(java.lang.object)' on a null object reference"

app version:3.1.2

![image](https://user-images.githubusercontent.com/60944721/189987905-910761cc-4eb9-4cde-9693-34e9ca685899.png)

**Comment by firemaples** [comment]
What's your device model and android OS version?

I found the same issue on another application: https://github.com/kkevsekk1/AutoX/issues/327
As their research, it happens on Xiaomi devices with MIUI 13 + Android 12

And from Firebase's console, it happens on POCO, Remi and Xiaomi devices

It's a headache issue, it seems the only way to resolve it is to request the screen recording permission every time you want to translate a text...

**Comment by firemaples** [comment]
Link with Firebase report
https://console.firebase.google.com/u/0/project/ever-translator/crashlytics/app/android:tw.firemaples.onscreenocr/issues/376df456c2a07f7823a23097a508200a?time=last-seven-days&types=error&versions=3.1.2%20(86)&sessionEventKey=631B92C602DE00014BE94D51B0A58191_1719909902439511825

**Comment by wres168** [comment]
Indeed, I'm using redmi k40 with MIUI13 & Android 12. I'll try updating the OS to see if that fixes the bug.
