### ISSUE TITLE
hyphenation

### ISSUE THREAD

**Issue by uomar8** [firemaples/EverTranslator#198]
A settings to remove dash at the end of the sentence
![5-with-justification-and-hyphenation (1)](https://user-images.githubusercontent.com/7046347/196031709-84f92c6d-3e37-4f34-8a5c-e92a166ed1dc.png)
![Screenshot_20221016-140151_Gallery](https://user-images.githubusercontent.com/7046347/196031717-075b6ee7-1582-4d5f-a8b8-8fad8254e2e5.jpg)
What the result should be 
![Screenshot_20221016-140209_Gallery](https://user-images.githubusercontent.com/7046347/196031737-a2cfe604-9cc8-43d5-8bd5-0c40a8a6bf19.jpg)

**Comment by firemaples** [comment]
Good suggestion and thanks for your feedback.
I'll add it in these days.

**Comment by firemaples** [comment]
It will be added in v3.1.4 and will be released on Google Play these days.
