### ISSUE TITLE
Notification is on

### ISSUE THREAD

**Issue by uomar8** [firemaples/EverTranslator#200]
After rebooting device the notification icon is on even though the app isn't on and it's not opened yet

![20221018_154839](https://user-images.githubusercontent.com/7046347/196434536-67b3a3c7-26d6-4cf5-bba7-7ed24b02387b.jpg)

It will work fine after open the app after reboot 

Android  9

**Comment by firemaples** [comment]
Thanks for the feedback.
I'll check it later!

**Comment by uomar8** [comment]
i founeded this
https://stackoverflow.com/questions/50526153/quick-settings-tile-in-active-state-on-boot-when-active-tile-enabled

but once i add 

<meta-data android:name="android.service.quicksettings.ACTIVE_TILE"
            android:value="true" />

and

TileService.requestListeningState(this,
            ComponentName(this, QuickTileService::class.java))

but off button change to on and on change to off

it might help

**Comment by firemaples** [comment]
Thank you for the survey, I'll check how to fix it.

**Comment by firemaples** [comment]
I found the problem.
The default state of quick tile items is active on Android 9.
And I used a `MutableSharedFlow` without assigning a default value, so it can be corrected after any state changes.
