### ISSUE TITLE
(Suggestions) View cropped image from OCR in edit OCR text

### ISSUE THREAD

**Issue by uomar8** [firemaples/EverTranslator#216]
Once you try to edit OCR text usually the page took the whole screen

Like this
![Screenshot_20221229_011412_com android chrome_edit_79515377218074](https://user-images.githubusercontent.com/7046347/209880250-13962e5c-36c5-48a6-b2a7-6245fcf5e785.jpg)

It would be great to show the cropped image above so you could easily fix the text like this 
![yfccyfycffty (20221229011537)_edit_79493066797244](https://user-images.githubusercontent.com/7046347/209880298-4a98197a-b41c-472a-a80a-9056b2451275.jpg)

**Comment by firemaples** [comment]
@uomar8 Cool! This is a great suggestion, I never think about it, let me put it on the list.
