### ISSUE TITLE
[suggestions] text detect using OpenCV

### ISSUE THREAD

**Issue by uomar8** [firemaples/EverTranslator#226]
There's a way to detect text using OpenCV here's the way to do it

https://www.geeksforgeeks.org/text-detection-and-extraction-using-opencv-and-ocr/amp/

And OpenCV support android
https://sourceforge.net/projects/opencvlibrary/files/4.6.0/
Also support kotlin 
https://philipplies.medium.com/setting-up-latest-opencv-for-android-studio-and-kotlin-2021-edition-259be404b133

What do you think could work?

**Comment by firemaples** [comment]
Great, it looks good to implement, but the library is a little large to wrap in an Android application.
Maybe it can be an extension application to avoid the current application taking too much space.

**Comment by uomar8** [comment]
> Great, it looks good to implement, but the library is a little large to wrap in an Android application. Maybe it can be an extension application to avoid the current application taking too much space.

You're right it's too large how about a this mini version of the library? 
https://github.com/nihui/opencv-mobile

What do  you think would be better to make extension application or to use mini library of it?

**Comment by firemaples** [comment]
> > Great, it looks good to implement, but the library is a little large to wrap in an Android application. Maybe it can be an extension application to avoid the current application taking too much space.
> 
> You're right it's too large how about a this mini version of the library? https://github.com/nihui/opencv-mobile
> 
> What do you think would be better to make extension application or to use mini library of it?

The size is okay after shrank, I can add it after doing a refactor on the modules.
