### ISSUE TITLE
[Suggestion] make HTML page for readme and version history and the app 

### ISSUE THREAD

**Issue by uomar8** [firemaples/EverTranslator#241]
I think moving readme and version history from inside the app to HTML page would 

-reduce the size of app 
-easier to update
-easier to add new pages
-could make the app easier to find through Google search
-easier to find the app page on social media 

It could be hosted on GitHub Pages

**Comment by firemaples** [comment]
This is a great suggestion, I'll enhance it later.

**Comment by firemaples** [comment]
https://pages.github.com/

Will do this in these days
