### ISSUE TITLE
[Question] why google play version is big compared to DEV version? 

### ISSUE THREAD

**Issue by uomar8** [firemaples/EverTranslator#243]
I think it's strange that google play version size more than DEV version

Google Play:
![Screenshot_20230119_165146](https://user-images.githubusercontent.com/7046347/213613848-0da80a17-32fe-4dc4-a23d-4e3791d43c29.jpg)

DEV:
![Screenshot_20230119_165106](https://user-images.githubusercontent.com/7046347/213613897-90fb0f4c-e6ea-400e-adba-5ac58aa51cee.jpg)

**Comment by firemaples** [comment]
This is the size info from the PlayStore backend
![image](https://user-images.githubusercontent.com/5812567/213728491-82578fd9-ec3e-40cc-8afe-3694426ca2b0.png)

I'm not sure why, but maybe the app is installed in ART mode from PlayStore, so it takes more space than the Dev version.
