### ISSUE TITLE
[bug] layouts doesn't support RTL languages 

### ISSUE THREAD

**Issue by uomar8** [firemaples/EverTranslator#251]
When it happens:

Once change the device language to RTL languages ( Arabic, Persian, Urdu.......)

Some layouts looks wrong and theses layouts are

1- menu: the menu is far from the button
How it looks and how it should
![Collage_20230125_031331](https://user-images.githubusercontent.com/7046347/214453002-208260f8-d29f-431d-948c-3f55a7ace5be.jpg)

2- floating result : it's not next to the word
![Collage_20230125_031531](https://user-images.githubusercontent.com/7046347/214452438-ed00dce4-57bb-4e23-b9f8-e028dc236667.jpg)

3- Floating menu: buttons are flipped
![Screenshot_20230125_031713](https://user-images.githubusercontent.com/7046347/214452756-579d3761-1c17-4818-949e-f1c96d3ee586.jpg)

4- browser buttons: back and forward are switched 
![Collage_20230125_032846](https://user-images.githubusercontent.com/7046347/214452809-111c8f19-3e55-438e-856c-4f81a30f49f5.jpg)

**Comment by firemaples** [comment]
About issues 1 and 2, the position of the views are calculated by myself and forgot to consider about the RTL mode 😫

**Comment by firemaples** [comment]
Is it still easy to use if disabling the RTL mode for RTL language users?

**Comment by uomar8** [comment]
> 

Yes what really matters is 

> Is it still easy to use if disabling the RTL mode for RTL language users?

Unfortunately no it won't be easy

For example perference.xml it will look very wrong 

Something like this
![xryryduf (20230125045646)](https://user-images.githubusercontent.com/7046347/214582418-84c44ade-d8c3-4111-b423-5494ea62fb38.jpg)

**Comment by firemaples** [comment]
I thought Google handled the RTL well by default, I think I don't customize anything on `preference.xml`. 😫

**Comment by uomar8** [comment]
> I thought Google handled the RTL well by default, I think I don't customize anything on `preference.xml`. 😫

Google can handle easy layouts 😆 your layout can move and change I don't think any time soon computer can handle it automatically
