### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by Yuiyoon** [firemaples/EverTranslator#335]
![Screenshot_2023-09-29-22-56-19-467_com android chrome](https://github.com/firemaples/EverTranslator/assets/146499651/772be205-1291-4675-8057-447588a1efba)

I tried it in some otome games I play by cybird and got this error so I tried in another app and still got this error

**Comment by firemaples** [comment]
Hi, thanks for the feedback. 
Could you share your phone's model and Android version? 🤔

**Comment by Yuiyoon** [comment]
> Hi, thanks for the feedback. Could you share your phone's model and Android version? 🤔

Xiaomi Poco X3 android 13

**Comment by Yuiyoon** [comment]
> Hi, thanks for the feedback. Could you share your phone's model and Android version? 🤔

**Comment by firemaples** [comment]
Hi @Yuiyoon, I prepared a version that may fix this issue, you can download the APK from https://github.com/firemaples/EverTranslator/actions/runs/6604019252
