### ISSUE TITLE
ResultView size changed

### ISSUE THREAD

**Issue by uomar8** [firemaples/EverTranslator#433]
ResultView size was fixed so it won't take much space of the screen
Before version 4.0.0
![20240205_220208](https://github.com/firemaples/EverTranslator/assets/7046347/9720c095-c431-41fd-96e1-2724b33a6532)

After version 4.0.0
![20240205_220237](https://github.com/firemaples/EverTranslator/assets/7046347/fe6c6f02-6459-4622-8c07-ab24774648e6)

I prefer the old one 😅

**Comment by firemaples** [comment]
Let me add a setting and make the default value the old one, limiting the width.
