### ISSUE TITLE
The main bar won't translucent automatically after clicking the menu button

### ISSUE THREAD

**Issue by uomar8** [firemaples/EverTranslator#443]
The main bar won't translucent automatically after clicking the menu button, it will hide again once it moved

https://github.com/firemaples/EverTranslator/assets/7046347/0e08144c-20ec-480f-b1c4-1fe3bec307d0

**Comment by uomar8** [comment]
> Thanks for reporting this issue.
> 
> I can not reproduce this on my Pixel 8 pro, let me try to find some other devices to test 🤔 I've upgraded the compose version to the latest one, please try this again on https://github.com/firemaples/EverTranslator/releases/tag/v4.0.4 🙇‍♂️

Still not fixed yet

**Comment by firemaples** [comment]
Ah, sorry, I think I misunderstood what you mean.

Do you mean the main bar does become translucent automatically after pressing the menu bar?

**Comment by uomar8** [comment]
> Ah, sorry, I think I misunderstood what you mean.
> 
> Do you mean the main bar does become translucent automatically after pressing the menu bar?

My apologies 😅 yes it doesn't translucent automatically

**Comment by firemaples** [comment]
Fixed in https://github.com/firemaples/EverTranslator/pull/450 🙇‍♂️
