### ISSUE TITLE
Menu button, edit ocr or web browser shows system bars in immersive mode (full screen mode)

### ISSUE THREAD

**Issue by uomar8** [firemaples/EverTranslator#452]
If the app in immersive mode (full screen mode) system bar shouldn't be seen after the menu button clicked, edit ocr or web browser

![IMG_20240407_083618](https://github.com/firemaples/EverTranslator/assets/7046347/fa7eea79-0d90-455c-aa8c-6117879d8289)
![Screenshot_20240407_084230_com android chrome](https://github.com/firemaples/EverTranslator/assets/7046347/2ff76a32-ec83-471a-88c0-ba234f8167e7)
![Screenshot_20240407_084240_com android chrome](https://github.com/firemaples/EverTranslator/assets/7046347/593d119e-c1c1-4241-9827-1a8794a0a1b1)

Video:

https://github.com/firemaples/EverTranslator/assets/7046347/71783b2b-d79f-4356-a6bc-2061e9d261af

In the video I used this website to start Fullscreen mode:
https://davidwalsh.name/demo/fullscreen.php

**Comment by firemaples** [comment]
I can try to fix the menu bar one by replacing the system one with a customized one as the version before compose refactoring.
But edit mode and web browser is not fixable since requesting focus shows the system bars, but the keyboard can only be displayed while requesting focus 🤔

**Comment by uomar8** [comment]
> I can try to fix the menu bar one by replacing the system one with a customized one as the version before compose refactoring. But edit mode and web browser is not fixable since requesting focus shows the system bars, but the keyboard can only be displayed while requesting focus 🤔

That's great 👍

Sorry this is not related to this issue😅
Could we use this with exit OCR? 

https://developer.android.com/develop/ui/views/touch-and-input/keyboard-input/visibility#ShowOnStart

**Comment by firemaples** [comment]
> > I can try to fix the menu bar one by replacing the system one with a customized one as the version before compose refactoring. But edit mode and web browser is not fixable since requesting focus shows the system bars, but the keyboard can only be displayed while requesting focus 🤔
> 
> That's great 👍
> 
> Sorry this is not related to this issue😅 Could we use this with edit OCR?
> 
> https://developer.android.com/develop/ui/views/touch-and-input/keyboard-input/visibility#ShowOnStart

Looks no, it's used on activity

**Comment by firemaples** [comment]
Please check, https://github.com/firemaples/EverTranslator/pull/453 should fix this issue for the menu on main bar
