### ISSUE TITLE
How to download the latest beta version

### ISSUE THREAD

**Issue by Gamefire238** [firemaples/EverTranslator#459]
Because what I saw on Playstore was still lagging behind on version 3... Meanwhile the one here is already version 4...?

**Comment by uomar8** [comment]
Go to 
https://play.google.com/apps/testing/tw.firemaples.onscreenocr?authuser=1

And click on "BECOME A TESTER"
![Screenshot_20240415_144858_edit_206316120133101](https://github.com/firemaples/EverTranslator/assets/7046347/8375fa0f-64f8-465e-98b6-86f7e3718af8)

**Comment by Gamefire238** [comment]
Good, thanks
